name = "gametestedtech"

compatibility_date = "2024-05-01"
compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = ".open-next/assets"

[vars]
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-1T725ZRJ6N"
NEXT_PUBLIC_SUPABASE_URL = "https://iqzmidqszkbtvkdaeyzg.supabase.co"